root = "."
testdata_dir = "testdata"
<<<<<<< HEAD
tmp_dir = "_build"

[build]
  args_bin = []
  bin = "./_build/customers start --config config.yaml "
  cmd = "go build -o ./_build/customers ."
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "_build"]
=======
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/customers start --config config.yaml "
  cmd = "go build -o ./tmp/customers ."
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
>>>>>>> air configuration
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
<<<<<<< HEAD
  log = "_build/errors.log"
=======
  log = "build-errors.log"
>>>>>>> air configuration
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
